### ISSUE TITLE
Temp roles aren't actually sending notifications

### ISSUE THREAD

**Issue by tehstone** [klords/Kyogre#65] opened 2018-10-10 03:28 UTC
Repro:
subscribe to wild beldum 
have someone else announce a wild beldum in a region you have assigned
tag will appear in channel but no notification will be sent

**Comment by klords** [comment] 2018-10-18 07:02
we can investigate this further to find what the root cause is, but ultimately this is a discord (configuration) issue, not with the bot, so closing for now

**Closed by klords** 2018-10-18 07:02 UTC
Labels: question
